### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by yekeqiang** [LittlePeng/redis-monitor#1]
when i visit the url http://ip:8888/, i  met with difficulties about '403: Forbidden'。and how can i see the log? where is the log path? when run daemon

**Comment by LittlePeng** [comment]
test http://ip:8888/index.html ?
2014年6月20日 下午6:24于 "yexiaobai" notifications@github.com写道：

**Comment by node** [comment]
Yeah, you should not visit http://ip:8888 instead of http:ip:8888/index.html because no default url mapping from index.html to /  , same as redis-live  :)

**Comment by GreatQing** [comment]
how to use the sms alert?
