### ISSUE TITLE
Error 500 when add multi redis intance

### ISSUE THREAD

**Issue by lieunn** [LittlePeng/redis-monitor#5]
Hi LittlePeng!
I build tool redis-monitor from your source , first I add 30 instance , result working OK, then I add about 100 redis instance , result server response status 500 loading (tab Overview).
Can you  help me fix error 500?
![redis_error_500](https://cloud.githubusercontent.com/assets/24824043/21541260/868c89d4-cde7-11e6-841f-2285c4d99a21.PNG)

This is debug log file get 500 error
Traceback (most recent call last):
      File "/usr/lib64/python2.6/site-packages/tornado/web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/build/redis-monitor/api/controller/InfoListController.py", line 16, in get
        info=self.getStatsPerServer((server['server'],server['port']))
      File "/build/redis-monitor/api/controller/BaseController.py", line 30, in getStatsPerServer
        slaves += info["slave" + (str)(i)]
    TypeError: cannot concatenate 'str' and 'dict' objects

**Comment by LittlePeng** [comment]
this error NOT for too many instance, redis-monitor not support lastest redis version.
in new redis version,  info command result format changed..

i fix it: https://github.com/LittlePeng/redis-monitor/commit/9f68bf9e6094c029536ddceb3895972e833d85eb
