### ISSUE TITLE
when I visit http://myip:8888/index.html, it return for me 404

### ISSUE THREAD

**Issue by hjkyoyo** [LittlePeng/redis-monitor#8]
Hi, Peng. Thanks for your great work, and I have a problem when I visit http://myip:8888/index.html. It return "404: Not Found" for me. Can you help me to resolve it?

**Comment by LittlePeng** [comment]
I have push a commit for bugfix, maybe you can try it.

**Comment by hjkyoyo** [comment]
Many thanks, it caused by losing some dependency you wrote in readme_ch.txt, I forgot to read it. Thanks for your reply!
